//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.27 at 04:51:57 PM BRST 
//


package br.com.fnogueira.xpdlparser.entity.dmn;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.fernando.importaxml.entity.dmn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.fernando.importaxml.entity.dmn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Definitions.Decision }
     * 
     */
    public Definitions.Decision createDefinitionsDecision() {
        return new Definitions.Decision();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable }
     * 
     */
    public Definitions.Decision.DecisionTable createDefinitionsDecisionDecisionTable() {
        return new Definitions.Decision.DecisionTable();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable.Rule }
     * 
     */
    public Definitions.Decision.DecisionTable.Rule createDefinitionsDecisionDecisionTableRule() {
        return new Definitions.Decision.DecisionTable.Rule();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable.Input }
     * 
     */
    public Definitions.Decision.DecisionTable.Input createDefinitionsDecisionDecisionTableInput() {
        return new Definitions.Decision.DecisionTable.Input();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable.Output }
     * 
     */
    public Definitions.Decision.DecisionTable.Output createDefinitionsDecisionDecisionTableOutput() {
        return new Definitions.Decision.DecisionTable.Output();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable.Rule.InputEntry }
     * 
     */
    public Definitions.Decision.DecisionTable.Rule.InputEntry createDefinitionsDecisionDecisionTableRuleInputEntry() {
        return new Definitions.Decision.DecisionTable.Rule.InputEntry();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable.Rule.OutputEntry }
     * 
     */
    public Definitions.Decision.DecisionTable.Rule.OutputEntry createDefinitionsDecisionDecisionTableRuleOutputEntry() {
        return new Definitions.Decision.DecisionTable.Rule.OutputEntry();
    }

    /**
     * Create an instance of {@link Definitions.Decision.DecisionTable.Input.InputExpression }
     * 
     */
    public Definitions.Decision.DecisionTable.Input.InputExpression createDefinitionsDecisionDecisionTableInputInputExpression() {
        return new Definitions.Decision.DecisionTable.Input.InputExpression();
    }

}
